Add Agent Deploy Selector workflow and refactor Velero backup workflow with IAM role configuration

diff --git a/.github/workflows/velero-backup.yaml b/.github/workflows/velero-backup.yaml
--- a/.github/workflows/velero-backup.yaml
+++ b/.github/workflows/velero-backup.yaml
@@ -4,19 +4,20 @@ on:
   workflow_dispatch:
     inputs:
       action:
-        description: 'Choose action: get-backup or restore-backup'
+        description: 'Choose action: list-backup, create-backup, or restore-backup'
         required: true
         type: choice
         options:
-          - get-backup
+          - list-backup
+          - create-backup
           - restore-backup
       backup_name:
-        description: 'Name of backup to restore (required for restore-backup)'
+        description: 'Name of backup to restore or create (required for restore-backup and create-backup)'
         required: false
 
 jobs:
-  get-backup:
-    if: ${{ github.event.inputs.action == 'get-backup' }}
+  list-backup:
+    if: ${{ github.event.inputs.action == 'list-backup' }}
     runs-on: ubuntu-latest
     steps:
       - name: Set up kubectl
@@ -36,8 +37,35 @@ jobs:
         env:
           KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
       - name: List Velero backups
+        run: velero backup get
+
+  create-backup:
+    if: ${{ github.event.inputs.action == 'create-backup' }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up kubectl
+        uses: azure/setup-kubectl@v3
+        with:
+          version: 'latest'
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-1
+      - name: Set up kubeconfig
         run: |
-            velero backup get
+          mkdir -p $HOME/.kube
+          echo "$KUBECONFIG_CONTENT" > $HOME/.kube/config
+        env:
+          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
+      - name: Create Velero backup
+        run: |
+          if [ -z "${{ github.event.inputs.backup_name }}" ]; then
+                echo "Error: backup_name input is required for create-backup"
+                exit 1
+                fi
+                velero backup create ${{ github.event.inputs.backup_name }} --use-restic --snapshot-volumes --exclude-resources secrets
 
   restore-backup:
     if: ${{ github.event.inputs.action == 'restore-backup' }}
